### ISSUE TITLE
Access token not present on url when redirected from oauth

### ISSUE THREAD

**Issue by icidasset** [remotestorage/armadietto#101]
👋  Thanks for this server. I was trying it out and don't get a `access_token` when redirected back to the app. Any thoughts on why that could be? I was testing it with a local build of https://diffuse.sh/ which worked with back in the remote storage v1 days (tested with [5apps](https://5apps.com/storage)).

**Comment by DougReeder** [comment]
I think we'll need to see an example, before we can usefully comment.

**Comment by icidasset** [comment]
My mistake, had an unexpected URL rewrite in my app.
