### ISSUE TITLE
client cannot sync server data

### ISSUE THREAD

**Issue by woodneko** [remotestorage/armadietto#14]
the data on the server has been updated, but cannot update on the client side
storage/
└── laverna~
    └── notes-db~
        ├── notebooks~
        │   ├── 07807626-f90d-d395-dd10-99856417f709
        │   ├── 1bd56c29-1bc1-0e84-2a29-7d85bd3846dd
        │   ├── 23eaeaa6-6ce1-15f4-113d-65fa541b42bd
        │   ├── 2bd12040-adb0-b2b1-6e2a-b1e93f72ae79
        │   ├── 7855b6ec-c93c-ad31-d8e1-56d960f9ae73
        │   ├── 87f87cda-1b30-d2ff-9a89-166271cce741
        │   └── e92116e3-3b96-dc1b-8cc6-edc4e2722cd3
        └── notes~
            ├── 059a5e58-efff-6751-6001-31f972c741a4
            ├── 0b9ff487-c34f-90db-17a3-e0f5c87d840c
            ├── 1970b843-e7f7-ab46-e2ef-531bfa499862
            ├── 1e2dd98e-4e53-f0c1-9fdb-2393741ac70b
            ├── 227534d3-17d8-1cd9-45c7-92bd9144484d
            ├── 2c258551-d746-4975-f647-80a5752ff8e2
            ├── 4145f07d-91ae-eed9-de8e-35021398ebdd
            ├── 6777abfd-b75d-b545-eaea-f7cbe261fd33
            ├── 7ee61fca-9c96-ff51-e111-efa98965e5db
            ├── 8e402ca0-1c91-3225-4f7a-86cec14637f2
            ├── 9bfe34c7-ef30-0a69-fbdf-014ce6b3b96a
            ├── a97c44cb-9411-f113-7292-bf85fb210651
            ├── b10fdf61-3217-d656-93e1-62250d08df5d
            ├── cc1f7afb-b38b-2bd7-9b13-e50ed38d6f04
            └── e42e6ff7-347e-7004-75e8-75f2fda6ccc2

4 directories, 22 files

server side configuration
start a remotestorage server with below config
{
  "allow_signup": true,
  "storage_path": "/root/path",
  "cache_views": true,
  "http": {
    "host": "xx.xx.xx.xx",
    "port": 8000
  }

when the client connect to server the generated auth.json information like below:
{
  "email": "xxx@xxxl.xxx",
  "password": {
    "salt": "Z7V4RAKKhQ+lcgvYbjC5Ag==",
    "work": 10000,
    "keylen": 64,
    "key": "O4hVRKKEE1osCky42kTCuJ+GGnk+zQGMacHAY/STj9nTCjGRPXoIrYkesbWArqEtFKKyWeRiVU4GaqTatyjYYQ=="
  },
  "sessions": {
    "Vq+U39F4rMTsQ2b4cRBnu7ZwQx8=": {
      "clientId": "http://localhost:9000",
      "permissions": {
        "/laverna/": {
          "r": true,
          "w": true
        }
      }
    }
  }
}

I guess the problem is on the clientid and path, but I don't know how to modify them?

**Comment by woodneko** [comment]
I ffind the reason not open the module FS the auth.json is right

**Comment by lesion** [comment]
Please consider this is a work in progress. I'm currently doing a complete rewrite in `feature/11-refactoring` branch

**Comment by woodneko** [comment]
another problem is that only running with root permission can sync note to cloud but both normal user and root user can sync note to local.
