### ISSUE TITLE
Update RS protocol support to latest version

### ISSUE THREAD

**Issue by skddc** [remotestorage/armadietto#3]
IIRC reStore still hadn't made the slightly bigger changes from -02, but I could be wrong. In general, we just need to check that it supports the latest stable version of the spec, which we can test using https://github.com/remotestorage/api-test-suite

**Comment by lesion** [comment]
remotestorage.js client is supporting the latest spec version?
which one it is?
are RS spec backward compatibles?

**Comment by skddc** [comment]
> remotestorage.js client is supporting the latest spec version?

Yes.

> which one it is?

The latest one is [`draft-dejong-remotestorage-10`](https://tools.ietf.org/html/draft-dejong-remotestorage-10). It's explained here: https://wiki.remotestorage.io/Protocol

> are RS spec backward compatibles?

They usually are. But there was a considerable change between -01 and -02 (iirc), which changed the format of the directory listings. remoteStorage.js still supports both versions (also iirc), but it's old enough that any other clients are not expected to support it anymore.

**Comment by lesion** [comment]
closing this as it's resolved [here](https://github.com/remotestorage/armadietto/pull/15).
There's also the new HEAD method
