### ISSUE TITLE
dependency updates

### ISSUE THREAD

**Issue by silverbucket** [remotestorage/armadietto#31]
Tried to update all dependencies but got in to some issues with the node.js `url` deprecation of the `parse` method, seems plugging in `url.URL` was breaking things. Didn't have time to try to resolve as all tests were breaking but wanted to make a not in case someone else has time to look this over.

**Comment by skddc** [comment]
Could you clarify this issue a bit, please?

[The current master branch seems to be green](https://travis-ci.org/remotestorage/armadietto), after you merged all those dependency updates from dependabot, as well as that old pull request, which also updated dependencies.

**Comment by silverbucket** [comment]
@skddc yeah master is fine. I created a local branch and tried to update all dependencies to their latest versions (including major releases) and after spending about an hour on it, it wasn't looking promising. If someone else picks this up it might be a better idea to do it in pieces, and I tried doing everything all at once.
