### ISSUE TITLE
Approved app listing

### ISSUE THREAD

**Issue by AngeloR** [remotestorage/armadietto#44]
Is it within the scope of the armadietto project to display all approved apps/permissions per user account? Or is this something better left to 3rd party tooling to implement?

Either way, it's probably something I'd want to take a stab at - just want to know where would be best.

**Comment by raucao** [comment]
Seems to me like this should be in scope for any RS server/account UI.

**Comment by AngeloR** [comment]
Perfect, thanks! 

Awesome work with the project btw, I can't believe I haven't heard of RS and I'm very excited to start contributing.

**Comment by AngeloR** [comment]
I've got a PR up that allows 

- A user to log in
- The logged in user can see all the applications they've approved, as well as the permissions granted to the apps
- They can see their storage account name

PR: #45
