### ISSUE TITLE
A sample unit file for systemd should be provided

### ISSUE THREAD

**Issue by DougReeder** [remotestorage/armadietto#65]
Is it possible to install such a file when `npm -g i armadietto` is run?

**Comment by DougReeder** [comment]
If I understand this correctly, no.
https://docs.npmjs.com/cli/v8/commands/npm-install#global

**Comment by raucao** [comment]
It's neither possible nor desired. An NPM module is not the same as an OS-level software package, and it's not meant to know the difference between for example systemd, launchd, or any other way of managing services on different operating systems, or in different environments like .e.g  containers versus VMs.

However, there could be an example file for a systemd unit, which someone creating e.g. deb or rpm packages could use in the actual system package, and also anyone deploying in other ways could copy and adapt.
